name: Build and Release Derper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Create build directory
        run: mkdir -p builds

      - name: Cross compile for different platforms
        run: |
          # Linux amd64
          GOOS=linux GOARCH=amd64 go install tailscale.com/cmd/derper@latest
          cp ~/go/bin/derper builds/derper-linux-amd64
          
          # Linux arm64
          GOOS=linux GOARCH=arm64 go install tailscale.com/cmd/derper@latest
          cp ~/go/bin/derper builds/derper-linux-arm64
          
          # Windows amd64
          GOOS=windows GOARCH=amd64 go install tailscale.com/cmd/derper@latest
          cp ~/go/bin/derper.exe builds/derper-windows-amd64.exe
          
          # macOS amd64
          GOOS=darwin GOARCH=amd64 go install tailscale.com/cmd/derper@latest
          cp ~/go/bin/derper builds/derper-darwin-amd64
          
          # macOS arm64
          GOOS=darwin GOARCH=arm64 go install tailscale.com/cmd/derper@latest
          cp ~/go/bin/derper builds/derper-darwin-arm64

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.TODAY }}
          name: Release ${{ steps.date.outputs.TODAY }}
          draft: false
          prerelease: false
          files: |
            builds/derper-linux-amd64
            builds/derper-linux-arm64
            builds/derper-windows-amd64.exe
            builds/derper-darwin-amd64
            builds/derper-darwin-arm64
